baseURL = 'https://buurland.netlify.app/'
languageCode = 'nl'

title = 'Buurland Utrecht'
theme = ['hyde', 'hugo-shortcode-gallery']

defaultContentLanguage = 'nl'
enableInlineShortcodes = true

summarylength = 10

paginate = 5

[params]
  description = "gemoedelijk wonen in hartje Utrecht"
  dateFormat = "mon 2 Jan 2006"


[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
[[menu.main]]
  identifier = 'buurtinbeeld'
  name = 'Buurt in Beeld'
  url = '/buurtinbeeld/'
  weight = 2
[[menu.main]]
  identifier = 'zwemfest'
  name = 'Zwemfest'
  url = '/zwemfest/'
  weight = 3
  [[menu.main]]
  identifier = 'verenigingbuurland'
  name = 'Vereniging Buurland'
  url = '/vereniging-buurland'
  weight = 4
[[menu.main]]
  identifier = 'media'
  name = 'In de media'
  url = '/categories/media/'
  weight = 5
[[menu.main]]
  identifier = 'blog'
  name = 'Berichten'
  url = '/categories/blog/'
  weight = 6
[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = 7  

