[context.deploy-preview.environment]
  HUGO_VERSION = "0.99.1"

[context.production.environment]
HUGO_VERSION = "0.99.1"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://smoelenboek.buurlandutrecht.nl"
  to = "https://docs.google.com/presentation/d/1h2RkaU0gB0hagqWy8G8sS0yEhXQDLQ_FrOb5LvZUvRo/edit?usp=drivesdk"
  status = 301
  force = true
