backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'berichten'
    label: 'berichten'
    folder: 'content/berichten'
    preview_path: "berichten/{{year}}{{month}}{{day}}-{{slug}}"
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'select', options: ["blog", "media"] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'media'
    label: 'in de media'
    folder: 'content/media'
    preview_path: "berichten/{{year}}{{month}}{{day}}-{{slug}}"
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }